// Product names, prices and artwork correspond to Figma node 2458:19517.
export const storeCategoryPages = {
  digital: {
    title: "다운로드로 시작하는 새로운 즐거움!",
    description: "마음에 드는 게임부터 추가 콘텐츠까지, 다양한 디지털 상품을 만나보세요.",
    height: 3165,
    rails: [
      { title: "Nintendo Switch2 - 디지털 상품", products: [
        {"name":"Maestro 마에스트로","price":"₩39,800","image":"443ea.png"},
        {"name":"스플래툰 레이더스","price":"₩64,800","image":"b5cbb.png"},
        {"name":"Pokémon Pokopia","price":"₩79,800","image":"419b8.png"},
        {"name":"Pokémon Pokopia 익스팬션 패스","price":"₩39,900","image":"3c754.png"},
        {"name":"파이어 엠블렘 만자천홍","price":"₩89,800","image":"b46f9.png"},
        {"name":"Meccha Chameleon","price":"₩8,300","image":"385ed.png"},
      ] },
      { title: "SALE", products: [
        {"name":"호그와트 레거시 Hogwarts Legacy","price":"₩7,980","image":"32c9f.png","originalPrice":"정가 ₩79,800"},
        {"name":"저스트 댄스 2026 에디션 - 스탠다드 에디션","price":"₩29,500","image":"d943c.png","originalPrice":"정가 ₩59,000"},
        {"name":"페르소나5 더 로열 (PERSONA5 THE ROYAL)","price":"₩20,940","image":"cff9e.png","originalPrice":"정가 ₩69,800"},
        {"name":"페르소나4 더 골든 (Persona 4 The Golden)","price":"₩11,880","image":"0f48e.png","originalPrice":"정가 ₩19,800"},
        {"name":"MONSTER HUNTER RISE + SUNBREAK 세트","price":"₩11,160","image":"79fbe.png","originalPrice":"정가 ₩69,800"},
        {"name":"FINAL, FANTASY VII REMAKE INTERGRADE","price":"₩12,450","image":"81d0e.png","originalPrice":"정가 ₩49,800"},
      ] },
      { title: "BEST", products: [
        {"name":"파이어 엠블렘 만자천홍","price":"₩89,800","image":"9ac15.png"},
        {"name":"Maestro 마에스트로","price":"₩39,800","image":"05058.png"},
        {"name":"Overcooked! All You Can Eat","price":"₩41,000","image":"4c277.png"},
        {"name":"사이버 펑크 2077: 얼티밋 에디션","price":"₩89,900","image":"51c9e.png"},
        {"name":"리듬 천국 미라클 스타즈","price":"₩64,800","image":"ada6b.png"},
        {"name":"디아블로 IV: 증오의 시대 컬렉션","price":"₩8,300","image":"60673.png"},
      ] },
      { title: "NEW", products: [
        {"name":"Party Party Time 3 Nintendo Switch 2 Edition","price":"₩5,000","image":"3d6b7.png"},
        {"name":"Flamecraft (플레임크래프트)","price":"₩19,350","image":"ffed4.png"},
        {"name":"LEGO® Batman™: 레거시 오브 더 다크나이트","price":"₩89,800","image":"e4c7f.png"},
        {"name":"Shape of Dreams","price":"₩22,400","image":"3d030.png"},
        {"name":"MONOWAVE","price":"₩9,720","image":"1c680.png"},
        {"name":"Aetherfall (에테르폴)","price":"₩5,940","image":"3f42e.png"},
      ] },
      { title: "무료 상품", products: [
        {"name":"Pokémon Champions","price":"₩0","image":"63ae0.png"},
        {"name":"오버워치™","price":"₩0","image":"5fb65.png"},
        {"name":"THE NEW DENPA MEN","price":"₩0","image":"b9cc6.png"},
        {"name":"아스팔트 레전드","price":"₩0","image":"496d6.png"},
        {"name":"Werewolf Online","price":"₩0","image":"dd820.png"},
        {"name":"가방 싸움","price":"₩0","image":"d1614.png"},
      ] },
    ],
  },
  physical: {
    title: "손 안에서 만나는 닌텐도의 즐거움!",
    description: "게임기부터 캐릭터 굿즈까지, 좋아하는 닌텐도를 직접 만나보세요!",
    height: 3286,
    rails: [
      { title: "Nintendo Switch2 - 실물 상품", products: [
        {"name":"Nintendo Switch 2","price":"₩758,000","image":"8d426.png"},
        {"name":"파이어 엠블렘 만자천홍","price":"₩98,000","image":"03090.png"},
        {"name":"파이어 엠블렘 만자천홍 Dagdan Collec tion","price":"₩148,000","image":"49b1a.png"},
        {"name":"오비탈스 Orbitals","price":"₩56,000","image":"7e4b4.png"},
        {"name":"Nintendo Switch Sports Resort 세트","price":"₩798,000","image":"836ff.png"},
        {"name":"Nintendo Switch Sports Resort + Joy-Con 2 세트","price":"₩68,000","image":"b21ef.png"},
      ] },
      { title: "피크민 굿즈 특집", products: [
        {"name":"배지 빨강 PIKMIN","price":"₩12,000","image":"40aa3.png"},
        {"name":"배지 노랑 PIKMIN","price":"₩12,000","image":"3a4f4.png"},
        {"name":"배지 파랑 PIKMIN","price":"₩12,000","image":"13121.png"},
        {"name":"배지 보라 PIKMIN","price":"₩12,000","image":"0895b.png"},
        {"name":"배지 하양 PIKMIN","price":"₩12,000","image":"68ca6.png"},
        {"name":"배지 날개 PIKMIN","price":"₩12,000","image":"eab0d.png"},
      ] },
      { title: "본체 & 주변기기", products: [
        {"name":"Nintendo Switch(OLED 모델) 화이트","price":"₩465,000","image":"d8479.png"},
        {"name":"Nintendo Switch(OLED 모델) 젤다의 전설 티어스 오브 더 킹덤 에디션","price":"","image":"33965.png"},
        {"name":"Nintendo Switch(OLED 모델) 스플래툰 3 에디션","price":"₩465,000","image":"dbc29.png"},
        {"name":"Nintendo Switch AC 어댑터","price":"₩33,800","image":"7930e.png"},
        {"name":"Nintendo Switch Pro 컨트롤러","price":"₩77,800","image":"74ce7.png"},
        {"name":"Nintendo Entertainment System™ 컨트롤러","price":"₩64,800","image":"45a86.png"},
      ] },
      { title: "굿즈 & 소프트웨어", products: [
        {"name":"리듬 천국 미라클 스타즈","price":"₩64,800","image":"657a3.png"},
        {"name":"수다쟁이 꽃","price":"₩48,800","image":"9feee.png"},
        {"name":"닌텐도 사운드 클록 Alarmo","price":"₩129,800","image":"dec87.png"},
        {"name":"친구모아 아일랜드 두근두근 라이프","price":"₩64,800","image":"72df5.png"},
        {"name":"모여봐요 동물의 숲","price":"₩64,800","image":"482a8.png"},
        {"name":"슈퍼 마리오 갤럭시 + 슈퍼 마리오 갤럭시 2","price":"₩74,800","image":"04846.png"},
      ] },
      { title: "플래티넘 포인트 교환 상품", products: [
        {"name":"프린세스 피치 Showtime! 5포켓 인덱스 클리어 파일","price":"300 Platinum","image":"825b2.png"},
        {"name":"포켓몬스터스칼렛 · 바이올렛 케이스 포함 형광펜 (2종)","price":"200 Platinum","image":"004c0.png"},
        {"name":"포켓몬스터스칼렛 · 바이올렛 B6 링노트","price":"300 Platinum","image":"018b9.png"},
        {"name":"모여봐요 동물의 숲 종이 봉투&종이 코스터","price":"300 Platinum","image":"957ee.png"},
        {"name":"동물의 숲 편지지 세트","price":"300 Platinum","image":"80855.png"},
        {"name":"별의 커비 Wii 디럭스 캔버스 파우치","price":"300 Platinum","image":"bc9a7.png"},
      ] },
    ],
  },
  online: {
    title: "함께할수록 더 커지는 즐거움!",
    description: "온라인 플레이부터 클래식 게임과 가입자 전용 혜택까지 만나보세요!",
    height: 4844,
    rails: [
      { title: "Nintendo Switch Online 이용권", products: [
        {"name":"Nintendo Switch Online 개인 플랜 1개월(30일간) 이용권","price":"₩5,900","image":"c3aea.png"},
        {"name":"Nintendo Switch Online 개인 플랜 12개월(365일간) 이용권","price":"₩24,900","image":"38f5c.png"},
        {"name":"Nintendo Switch Online 패밀리 플랜 12개월(365일간) 이용권","price":"₩47,900","image":"27ecb.png"},
      ] },
      { title: "Nintendo Switch Online + 추가 팩 이용권", products: [
        {"name":"Nintendo Switch Online + 추가 팩 개인 플랜 12개월(365일간) 이용권","price":"₩49,900","image":"9ae8f.png"},
        {"name":"Nintendo Switch Online + 추가 팩 패밀리 플랜 12개월(365일간) 이용권","price":"₩84.900","image":"2be9d.png"},
      ] },
      { title: "Nintendo Switch Online 가입자 한정 소프트웨어", products: [
        {"name":"TETRIS® 99","price":"₩0","image":"8ee8c.png"},
        {"name":"F-ZERO 99","price":"₩0","image":"0578d.png"},
        {"name":"Nintendo Entertainment System – Nintendo Classics","price":"₩0","image":"6a1ca.png"},
        {"name":"Nintendo Entertainment System – Nintendo Classics","price":"₩0","image":"d0c77.png"},
        {"name":"Super Nintendo Entertainment System – Nintendo Classics","price":"₩0","image":"a5873.png"},
      ] },
      { title: "추가팩 가입자라면 무료로 즐길 수 있는 소프트웨어", products: [
        {"name":"Virtual Boy – Nintendo Classics","price":"₩0","image":"29a7a.png"},
        {"name":"젤다의 전설 브레스 오브 더 와일드 Nintendo Switch 2 Edition 업그레이드 패스","price":"₩10,000","image":"ad27e.png"},
        {"name":"젤다의 전설 티어스 오브 더 킹덤 Nintendo Switch 2 Edition 업그레이드 패스","price":"₩10,000","image":"72328.png"},
        {"name":"마리오 카트 8 디럭스 - 부스터 코스트 패스","price":"₩25,000","image":"480ae.png"},
        {"name":"모여봐요 동물의 숲 해피 홈 파라다이스","price":"₩25,000","image":"f7db2.png"},
        {"name":"Spatoon 2: Octo Expansion","price":"₩19,800","image":"09821.png"},
      ] },
      { title: "Nintendo Switch Online 가입자 한정 상품", products: [
        {"name":"Virtual Boy for Nintendo Switch 2 /Nintendo Switch","price":"₩99,800","image":"ec37f.png"},
        {"name":"Virtual Boy(페이퍼 모델) for Nintendo Switch 2/Nintendo Switch","price":"₩34,800","image":"147b4.png"},
        {"name":"Nintendo GameCube 컨트롤러","price":"₩82,800","image":"ec923.png"},
        {"name":"Nintendo 64 컨트롤러","price":"₩54,800","image":"2930e.png"},
        {"name":"Super Nintendo Entertainment System™ 컨트롤러","price":"₩34,800","image":"b0fc0.png"},
        {"name":"Nintendo Entertainment System™ 컨트롤러","price":"₩64,800","image":"1ddb9.png"},
      ] },
    ],
  },
  feature: {
    title: "게임을 더 다양하게 즐기는 방법!",
    description: "업그레이드 패스부터 체험판, 추천 소프트웨어까지 특별한 게임 정보를 확인해 보세요.",
    height: 2336,
    rails: [
      { title: "업그레이드 패스 소개", products: [
        {"name":"Woodo - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩0","image":"e2e66.png"},
        {"name":"라면 가게 스토리(The Ramen Sensei) - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩4,500","image":"cb014.png"},
        {"name":"Asdivine Knot - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩0","image":"98ce7.png"},
        {"name":"Lou’s Lagoon - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩0","image":"4ce48.png"},
        {"name":"Pipistrello and the Cursed Yoyo - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩0","image":"ff7f7.png"},
        {"name":"1000xRESIST - Nintendo Switch 2 Edition 업그레이드 패스","price":"₩0","image":"212ba.png"},
      ] },
      { title: "체험판 소프트웨어 특집", products: [
        {"name":"네모바지 스폰지밥: 바다의 거인들","price":"₩44,800","image":"062e3.png"},
        {"name":"몬스터 퀘스트 몬스터즈4 메마른 나라의 비앙카와 플로라","price":"₩69,800","image":"17e31.png"},
        {"name":"Maestro 마에스트로","price":"₩39,800","image":"d40a1.png"},
        {"name":"스타폭스","price":"₩54,800","image":"d10e4.png"},
        {"name":"요시의 신기한 도감","price":"₩69,800","image":"c7a16.png"},
        {"name":"FINAL FANTASY RESONANCE","price":"₩62,800","image":"81962.png"},
      ] },
      { title: "Nintendo Switch Pick up", products: [
        {"name":"리듬 천국 미라클 스타즈","price":"₩64,800","image":"c894d.png"},
        {"name":"친구모아 아일랜드 두근두근 라이프","price":"₩64,800","image":"d353e.png"},
        {"name":"모여봐요 동물의 숲","price":"₩64,800","image":"49873.png"},
        {"name":"Nintendo Switch Sports","price":"₩44,800","image":"ca61e.png"},
        {"name":"피크민 3 디럭스","price":"₩64,800","image":"1a69d.png"},
        {"name":"Pokémon LEGENDS Z-A","price":"₩69,800","image":"27700.png"},
      ] },
    ],
  },
};
